#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'erp42-description','console_scripts','front_camera_viewer'
__requires__ = 'erp42-description'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('erp42-description', 'console_scripts', 'front_camera_viewer')()
    )
