controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

forward_position_controller:
  ros__parameters:
    joints:
      - lf_steering_hinge_joint
      - rf_steering_hinge_joint
    interface_name: position

velocity_controller:
  ros__parameters:
    joints:
      - left_back_wheel_joint
      - right_back_wheel_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
