joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

forward_position_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints: [lf_steering_hinge_joint, rf_steering_hinge_joint]
    interface_name: position
    use_sim_time: true

velocity_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints: [left_front_wheel_joint, left_back_wheel_joint, right_front_wheel_joint, right_back_wheel_joint]
    use_sim_time: true