update_rate: 100

joint_state_broadcaster.type: joint_state_broadcaster/JointStateBroadcaster

diff_cont.type: diff_drive_controller/DiffDriveController
diff_cont.base_frame_id: structure
diff_cont.left_wheel_names: ["left_front_wheel_joint", "left_back_wheel_joint"]
diff_cont.right_wheel_names: ["right_front_wheel_joint", "right_back_wheel_joint"]
diff_cont.wheel_separation: 0.6
diff_cont.wheel_radius: 0.28

diff_cont.linear.x.has_velocity_limits: true
diff_cont.linear.x.max_velocity: 0.2
diff_cont.linear.x.has_acceleration_limits: true
diff_cont.linear.x.max_acceleration: 0.6

diff_cont.angular.z.has_velocity_limits: true
diff_cont.angular.z.max_velocity: 2.0
diff_cont.angular.z.has_acceleration_limits: true
diff_cont.angular.z.max_acceleration: 6.0

diff_cont.pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
diff_cont.twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

diff_cont.use_stamped_cmd_vel: False
